name: QUGaR
channels:
  - conda-forge
dependencies:
  # Explicit pins for compatibility
  - python >=3.11,<3.13        # dolfinx 0.9.0 supports <=3.12 very reliably on conda-forge
  - fenics-dolfinx ==0.9.0

  - mpich
  - pyvista
  - scipy
  - liblapacke
  - openblas

  - scikit-build-core
  - cmake
  - ninja
  - catch2
  - doxygen
  - nanobind

  - sphinx
  - breathe
  - myst-parser
  - markdown

  - ipython
  - pytest
  - jupytext
  - pip
  - pip:
      - sphinx-rtd-dark-mode

